### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by avgKol** [solarwinds/fluent-plugin-papertrail#10]
When I execute 
https://raw.githubusercontent.com/solarwinds/fluent-plugin-papertrail/master/kubernetes/fluentd-daemonset-papertrail.yaml

I get the following error 
```
daemonset "fluentd-papertrail-global-logging" created
error: error converting YAML to JSON: yaml: line 20: did not find expected key
```
Also , the pod fails with error
```
MountVolume.SetUp failed for volume "config" : configmaps "fluentd-papertrail-global-logging-config" not found
```

**Comment by alexouzounis** [comment]
Hi @avgKol - thanks for submitting the issue.

Could you provides us with the contents of the file you were trying to apply ? There is probably a misaligned tab in the yaml file when commenting out the necessary fields

**Comment by cmrust** [comment]
Hey @avgKol, I would suggest removing all of the lines that are commented out in the ConfigMap portion of that yaml, at the bottom.

I was just able to recreate this error by deploying the combined DaemonSet/ConfigMap yaml as-is. Removing the commented lines in the ConfigMap solved the issue for me. Please let me know if that suffices and we can consider another way to suggest matching `kube-apiserver-audit` logs to users.

**Comment by cmrust** [comment]
Moved Audit logging details to the README file. @avgKol, if this doesn't suffice, please feel free to reopen this issue.
