### ISSUE TITLE
Orphaned Namespace

### ISSUE THREAD

**Issue by lswith** [solarwinds/fluent-plugin-papertrail#16]
The logs in our papertrail look like this:
```
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd:   </parse>
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd: </filter> is not used.
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd: 2018-05-03 06:26:48 +0000 [warn]: parameter 'include_namespace_metadata' in <filter kubernetes.**>
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd:   type kubernetes_metadata
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd:   include_namespace_metadata true
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd:   annotation_match ["solarwinds.io/*"]
May 03 16:26:50 staging-.orphaned-fluentd-papertrail-global-logging-rqnjj fluentd: </filter> is not used.
```

The namespace created in papertrail is `.orphaned`.

The file its tailing is:
`/var/log/containers/fluentd-papertrail-global-logging-rqnjj_kube-system_fluentd-d2648d90a647ef1b90b4e48514521e26c1322793d99331082a8c3fe02757372d.log`. 

Docker version:
quay.io/solarwinds/fluentd-kubernetes:v1.1.1-debian-papertrail-0.2.3
Kubernetes Version: 1.10

**Comment by lswith** [comment]
it seems that the counter `namespace_cache_api_nil_error` is going up on each log which indicates that this line: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/b31268ffc1ad6cc4ebe0fde9dfd147bf76271ed9/lib/fluent/plugin/filter_kubernetes_metadata.rb#L142:42 is the issue

**Comment by lswith** [comment]
i think this could do with having RBAC enabled. The plugin fetches the namespace metadata from the api server.

**Comment by lswith** [comment]
yeah you need RBAC permissions:
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-logging
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-logging
subjects:
- kind: ServiceAccount
  name: fluentd-logging
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-logging
  namespace: kube-system
---
```

**Comment by cmrust** [comment]
Thanks @lswith for the RBAC example. I'll reopen this issue to get this included in the README.

**Comment by leecalcote** [comment]
Agree. Thanks for reopening, @cmrust.

**Comment by cmrust** [comment]
The Kubernetes install instructions have since moved to a new repo.

This PR adds these instructions there: https://github.com/solarwinds/fluentd-deployment/pull/7
