### ISSUE TITLE
maximum_syslog_packet_size default value exceeded 

### ISSUE THREAD

**Issue by bmihaescu** [solarwinds/fluent-plugin-papertrail#30]
Hi,

I have set the default value for maximum_syslog_packet_size witch is 99990.
What will happen with my log packet if I will exceed that value. 
It will be truncated or just ignored ?

Thanks

**Comment by kyleroot** [comment]
It will be truncated. 

I found that value in the remote_syslog2 shipper that SolarWinds provides. The "official" by-the-book limit for syslog is 1024. The value is a `config_param` so you could try setting it to a larger value, however I have no idea what the cutoff for Papertrail is, or how efficiently they process values larger than 99990 bytes.

The config field to set in your `fluent.conf` would be `maximum_syslog_packet_size`.

```
    config_param :maximum_syslog_packet_size, :integer, default: 99990
```
