### ISSUE TITLE
Logging stalls due to unexpected records

### ISSUE THREAD

**Issue by markdascher** [solarwinds/fluent-plugin-papertrail#9]
This works great as long as each record includes all five [required fields](https://github.com/solarwinds/fluent-plugin-papertrail/blob/master/lib/fluent/plugin/out_papertrail.rb#L53-L57). But as soon as one record is missing something, fluentd enters an error loop and stops forwarding logs:

```
[warn]: temporarily failed to flush the buffer. error="Hostname may not be omitted"
```

The most foolproof fix would be to modify the out_papertrail plugin to fill in reasonable defaults for each field. Another option would be to modify the [fluentd configuration](https://github.com/solarwinds/fluent-plugin-papertrail/tree/master/docker/conf) to collect fewer files or transform everything to ensure the five fields are present (like [this](https://github.com/solarwinds/fluent-plugin-papertrail/blob/master/docker/conf/kubernetes.conf#L157-L169)).

**Comment by peterkuiper** [comment]
Having the same problem:

    2018-03-07 09:17:33 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-03-07 09:19:28 +0000 error_class="ArgumentError" error="Hostname may not be omitted" plugin_id="object:2ad98573e374"

I have to restart all the pods to get things going again.

**Comment by alexouzounis** [comment]
a solution is to change your [fluent.conf](kubernetes/fluentd-daemonset-papertrail.yaml#L90) match to only kubernetes related logs ie

```
<match kubernetes.*>
  type papertrail
  papertrail_host <your papertrail hostname>
  papertrail_port <your papertrail port>
</match>

<match systemd.*>
  type papertrail
  papertrail_host <your papertrail hostname>
  papertrail_port <your papertrail port>
</match>
```

instead of the match all

**Comment by cmrust** [comment]
Hey @markdascher, we've taken your suggested approach and set reasonable defaults for the required fields. Please give this a shot again and reopen the issue if you're still having any problems.
